spring:
 profiles.active: uat

 freemarker:
    template-loader-path: /
    suffix: .ftl             
    
 messages:
    basename: validation  
    
application:
  title: UnlockJava - Java Tutorial Important Interview FAQ, JAVA Internal Implementations
  desc: UnlockJava gives you fully unlocked access to Java Concepts, Latest Interview Questions, Answers, Java Interview Programs. Deep Tutorials on Spring, Hibernate, RestFul Web Services, SOAP, Servlet, JSP, Freemarker, Velocity
  auther: UnlockJava TM
  keywords: UnlockJava TM
url:
  badwords: a, about, above, after, again, against, all, am, an, and, any, are, as, at, be, because, been, before, being, below, between, both, but, by, could, did, do, does, doing, down, during, each, few, for, from, further, had, has, have, having, he, he'd, he'll, he's, her, here, here's, hers, herself, him, himself, his, how, how's, i, i'd, i'll, i'm, i've, if, in, into, is, it, it's, its, itself, let's, me, more, most, my, myself, nor, of, on, once, only, or, other, ought, our, ours, ourselves, out, over, own, same, she, she'd, she'll, she's, should, so, some, such, than, that, that's, the, their, theirs, them, themselves, then, there, there's, these, they, they'd, they'll, they're, they've, this, those, through, to, too, under, until, up, very, was, we, we'd, we'll, we're, we've, were, what, what's, when, when's, where, where's, which, while, who, who's, whom, why, why's, with, would, you, you'd, you'll, you're, you've, your, yours, yourself, yourselves

 
--- 
spring:
 profiles: dev
 
 jpa:
  hibernate:
    show_sql: true
    ddl-auto: true
    format_sql: true
    type: trace   
    dialect: org.hibernate.dialect.MySQLDialect
    connection.pool_size: 10
 
 
 datasource:
    driver: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sys?sessionVariables=sql_mode='NO_ENGINE_SUBSTITUTION'&jdbcCompliantTruncation=false
    username: root
    password: root

---
spring:
 profiles: uat
 
 jpa:
  hibernate:
    show_sql: true
    ddl-auto: true
    format_sql: true
    type: trace   
    dialect: org.hibernate.dialect.MySQLDialect
    connection.pool_size: 10
 
 
 datasource:
    driver: com.mysql.jdbc.Driver
    url: jdbc:mysql://db4free.net:3306/dibyajyoti
    username: dibyajyoti
    password: 12345678#uj
    
---
spring:
 profiles: prod
 
 jpa:
  hibernate:
    show_sql: true
    ddl-auto: true
    format_sql: true
    type: trace   
    dialect: org.hibernate.dialect.MySQLDialect
    connection.pool_size: 10
 
 
 datasource:
    driver: com.mysql.jdbc.Driver
    url: jdbc:mysql://139.162.56.56:3306/unlockjava_prod?sessionVariables=sql_mode='NO_ENGINE_SUBSTITUTION'&jdbcCompliantTruncation=false
    username: unlockjava_admin
    password: EJ9))l4]A%-B

#management.security.enabled=false